"""
Django settings for {{cookiecutter.project_name}} project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from .base import *
from .applications import *
from .authentication import *
from .internationalization import *


# Use of production settings if present
try:
    from .production import *
except ModuleNotFoundError:
    print(
        "\033[93m\033[1mWARNING:",
        "You are using development settings.",
        "Remember to add a production.py file if you are in production.",
        "\033[0m"
    )
    try:
        from .development import *
    except ModuleNotFoundError:
        raise ModuleNotFoundError(
            "Missing development.py file in settings. You must create a development.py files in the settings folder."
        )
